version: "3.1"

services:
  db:
    image: mysql:latest
    container_name: mvc-express_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mvc_example
    ports:
      - 3306:3306
    volumes:
      - ./mvc_example.sql:/docker-entrypoint-initdb.d/mvc_example.sql